name: "Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_RUNNER_DEBUG: true
  NODE_OPTIONS: "--openssl-legacy-provider --disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning"

jobs:
  changesets:
    name: "Changesets ðŸ¦‹"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: "ðŸ”‘ Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: "Export Node Version Priority"
        run: echo "$RUNNER_TOOL_CACHE/node/22*/x64/bin" >> $GITHUB_PATH

      - name: "Clear npm Auth Tokens"
        # actions/setup-node@v6 automatically adds npm auth tokens
        # but we publish using GitHub Trusted Publisher
        # so npm auth tokens cause problems
        run: |
          echo "NPM_TOKEN=" >> $GITHUB_ENV
          echo "PROVENANCE=" >> $GITHUB_ENV
          echo "NODE_AUTH_TOKEN=" >> $GITHUB_ENV
          echo "NPM_CONFIG_TOKEN=" >> $GITHUB_ENV
          echo "NPM_CONFIG_USERCONFIG=.npmrc" >> $GITHUB_ENV

      - name: "Install Dependencies"
        run: |
          # update npm to latest
          npm add --global npm@latest
          # Setup Bun
          npm add --global bun@latest
          # Install Deps
          bun install --frozen-lockfile

      - name: "Ensure Node.js in PATH & v22"
        # install Node.js v22 if not present in PATH
        run: |
          if ! echo "$PATH" | grep -q "$RUNNER_TOOL_CACHE/node/22*/x64/bin"; then
            npm add --global node@22
          fi
          # export Node.js v22 to PATH globally
          echo "$RUNNER_TOOL_CACHE/node/22*/x64/bin" >> $GITHUB_PATH
          echo "::add-path::$GITHUB_PATH"
          # verify Node.js is v22
          node --version | grep -q "v22"
          if [ $? -ne 0 ]; then
            echo "Node.js is not v22"
            exit 1
          fi

      - name: "Setup Git"
        run: |
          git config --local user.name "o-az"
          git config --local user.email "omaraziz.dev@gmail.com"

      - name: "Pull Request || Publish"
        id: changesets
        uses: changesets/action@v1
        env:
          NPM_CONFIG_USERCONFIG: .npmrc
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: bun changeset:publish
          version: bun changeset:version
          title: "chore: version package"
          commit: "chore: version package"
          setupGitUser: false
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}

      - name: "Publish Canary Release"
        if: steps.changesets.outputs.published != 'true'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git reset --hard origin/main
          bun clean
          bun changeset version --no-git-tag --snapshot canary
          bun changeset:prepublish
          bun changeset publish --no-git-tag --snapshot canary --tag canary
