name: "Publish"

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ACTIONS_RUNNER_DEBUG: true
  NODE_OPTIONS: "--openssl-legacy-provider --disable-warning=ExperimentalWarning --disable-warning=DeprecationWarning"

jobs:
  changesets:
    name: "Changesets ðŸ¦‹"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: "ðŸ”‘ Checkout"
        uses: actions/checkout@v6

      - name: "Setup Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "latest"
          registry-url: "https://registry.npmjs.org"

      - name: "Install Dependencies"
        run: |
          # Setup Bun
          npm add --global bun@latest
          # Install Deps
          bun install --frozen-lockfile

      - name: "Setup Git"
        run: |
          git config --local user.name "o-az"
          git config --local user.email "omaraziz.dev@gmail.com"

      - name: "Pull Request || Publish"
        id: changesets
        uses: changesets/action@v1
        with:
          publish: bun changeset:publish
          version: bun changeset:version
          title: "chore: version package"
          commit: "chore: version package"
          setupGitUser: false
          createGithubReleases: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.CHANGESETS_TOKEN }}

      - name: "Publish Canary Release"
        if: steps.changesets.outputs.published != 'true'
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git reset --hard origin/main
          bun clean
          bun changeset version --no-git-tag --snapshot canary
          bun changeset:prepublish
          bun changeset publish --no-git-tag --snapshot canary --tag canary
